
    /*
    ***************************************************************************
    *  Copyright 2008 Impinj, Inc.
    *
    *  Licensed under the Apache License, Version 2.0 (the "License");
    *  you may not use this file except in compliance with the License.
    *  You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    *  Unless required by applicable law or agreed to in writing, software
    *  distributed under the License is distributed on an "AS IS" BASIS,
    *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    *  See the License for the specific language governing permissions and
    *  limitations under the License.
    *
    ***************************************************************************
    */


    /*
    ***************************************************************************
    *
    *  This code is generated by Impinj LLRP .Net generator. Modification is
    *  not recommended.
    *
    ***************************************************************************
    */

    /*
    ***************************************************************************
    * File Name:       LLRPParam.cs
    *
    * Version:         1.0
    * Author:          Impinj
    * Organization:    Impinj
    * Date:            Jan. 18, 2008
    *
    * Description:     This file contains LLRP parameter definitions
    ***************************************************************************
    */

    namespace Org.LLRP.LTK.LLRPV1
    {
    public class LLRPVendorConstants
    {
      public const string NAMESPACE_PREFIX = "thingmagic";
      public const string NAMESPACE_URI = "http://www.thingmagic.com/ltk/schema/extension/xml/1.0/";
      public const string NAMESPACE_SCHEMALOCATION = "http://www.thingmagic.com/ltk/schema/extension/xml/1.0/thingmagic.xsd";
      public const string VENDOR_NAME = "thingmagic";
      public const string VENDOR_ID = "26554";
    }
    }
  